### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by ricko2991** [ScRiPt1337/ATANK#1]
No description provided, And the video is has been removed.

**Comment by Morsmalleo** [comment]
Yes it is a bit annoying knowing that you would have to figure out how to build it yourself, fortunately I have figured it out and the steps are below with screenshots as well if you get confused

Step 1: Git clone ATANK as shown below 
![Step 1](https://user-images.githubusercontent.com/64344168/104157464-2a613180-53b9-11eb-927f-65ab25ace416.png)

Step 2: cd into the ATANK folder as shown below
![Step 2](https://user-images.githubusercontent.com/64344168/104157566-66949200-53b9-11eb-9729-a1c54c9fa611.png)

Step 3: Open the ATANK folder from where ever you git cloned it to, you can use the command `exo-open` to do this, as shown below
![Step 3](https://user-images.githubusercontent.com/64344168/104158049-87a9b280-53ba-11eb-8cbe-67d38569982b.png)

Step 4: As you can see from the screenshot in Step 3, there is a `main` file and a `setup` file, rename them to `setup.sh` and `main.sh` as shown below
![step 4](https://user-images.githubusercontent.com/64344168/104158212-deaf8780-53ba-11eb-89c9-46e0e55e7317.png)

Step 5: Close the ATANK window and return to your terminal, then type `sudo ./setup.sh` once setup is finished type `sudo ./main.sh` 

and boom you have ATANK
